name: flow of control
favicon: null
layout_spectrum: 0.7708152586128563
typography_spectrum: 0.8787479000166059
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120f0a'
    - '#849fd6'
    - '#605331'
    - '#fffce9'
    - '#e6cc57'
  brandStrength: 0.8654736839234829
  lightness: 0.5442673154175282
  saturation: 0.34952053404413164
  rhythmicContrast: 0.9560723265167326
purpose: []
